### ISSUE TITLE
글 목록 - 로그인 요구 페이지 분류

### ISSUE THREAD

**Issue by kim-do-kyun** [Minuring/KSSoftware#50]
### 🔨 Describe

자료 게시판 이외의 기타 유틸(중고 거래 제외)과 자유게시판은 비회원도 접근 가능하게 변경

### ✅ Tasks

- [x] 자유게시판
- [x] 기타유틸
    - [x] 학점 계산기
    - [x] 스터디

**Comment by Minuring** [comment]
완료
